name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  DEFAULT_ELIXIR_VERSION: '1.14'
  DEFAULT_OTP_VERSION: '25'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.DEFAULT_ELIXIR_VERSION }}
          otp-version: ${{ env.DEFAULT_OTP_VERSION }}
      - run: mix deps.get --only
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused

  test:
    name: Test (OS ${{matrix.os}} | Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      # Test each supported Elixir minor version. For each Elixir version,
      # use the latest OTP and latest of each supported OS
      # https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp
      # https://hexdocs.pm/elixir/1.14.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        os: [ubuntu-22.04, windows-2022]
        elixir: ['1.12', '1.13', '1.14']
        include:
          - otp: '25'
          - otp: '24'
            elixir: '1.12'
    env:
      MIX_ENV: test
    steps:
      - name: Configure Git
        # doctest fails on Windows without
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get --only
      - run: mix compile --warnings-as-errors
      - run: mix test --cover --export-coverage ci --trace --warnings-as-errors
      - run: mix test.coverage
      - name: Coveralls
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate docs
        run: |
          mix docs
          test -f doc/index.html && echo "doc/index.html exists."


  # https://github.com/jeremyjh/dialyxir#github-actions
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
    steps:
      - uses: actions/checkout@v2
      - id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.DEFAULT_ELIXIR_VERSION }}
          otp-version: ${{ env.DEFAULT_OTP_VERSION }}
      - id: plt_cache
        uses: actions/cache@v2
        with:
          path: _build/${{env.MIX_ENV}}/dialyxir_*
          key: plt-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}
          restore-keys: plt-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}
      - run: mix deps.get --only
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt --format github
        # `--force-check` should not be necessary here since it checks the hash
        # https://github.com/jeremyjh/dialyxir/blob/231d61c77bb23f3015af87b4850fe7ebecd1e07d/lib/mix/tasks/dialyzer.ex#L250
      - run: mix dialyzer --format github
